version: '3.1'
services:
  eureka:
    image: "eureka:latest"
    environment:
      EUREKA_HOSTNAME: eureka
    ports:
      - "8761:8761"
  gateway:
    image: "gateway:latest"
    environment:
      EUREKA_HOSTNAME: eureka
    ports:
      - "8080:8080"
  articles:
    image: "articles:latest"
    environment:
      SPRING_ARGS: --info.version=1.0.0
      JAVA_ARGS: -XX:+UnlockExperimentalVMOptions -XX:+UseZGC
      EUREKA_HOSTNAME: eureka
      DB_HOST: postgresql
      DB_USER: postgres
      DB_PASSWORD: secret123
      DB: demo
    ports:
      - "8080"
    depends_on:
      - postgresql
  postgresql:
    image: "postgres:12.2-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
