server:
  port: 8761

eureka:
  instance:
    preferIpAddress: false
    hostName: ${EUREKA_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostName}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

info:
  version: ${VERSION:latest}
  name: eureka

logging:
  level:
    com:
      netflix:
        eureka: OFF