server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

info:
  version: ${VERSION:latest}
  name: articles

logging.level.org.springframework: ERROR

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB:demo}?currentSchema=${spring.flyway.schemas}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret123}
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: articles

---
spring:
  profiles: develop

logging.level.org.springframework: WARN

server:
  port: 8085

eureka:
  client:
    enabled: false